apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-file
spec:
  selector: { matchLabels: { app: postgres-file } }
  template:
    metadata: { labels: { app: postgres-file } }
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        env:
        - { name: POSTGRES_DB, value: {{ .Values.postgres.file.db | quote }} }
        - { name: POSTGRES_USER, value: {{ .Values.postgres.file.user | quote }} }
        - name: POSTGRES_PASSWORD
          valueFrom: { secretKeyRef: { name: {{ .Release.Name }}-secrets, key: POSTGRES_FILE_PASSWORD } }
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-file
spec:
  ports: [{ port: 5432 }]
  selector: { app: postgres-file }
